version: 0.0
os: linux

files:
  - source: scripts
    destination: /home/ubuntu/iic2173-2021-2-g14
permissions:
  - object: scripts
    pattern: "**"
    owner: ubuntu


hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 600
      runas: ubuntu
  AfterInstall:
    - location: scripts/install.sh
      timeout: 600
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 600
      runas: ubuntu
