version: 0.0
os: linux

files:
  - source: scripts
    destination: /home/ubuntu/iic2173-2021-2-g14
permissions:
  - object: scripts
    pattern: "**"
    owner: ubuntu


hooks:
  ApplicationStop:
    - location: stop.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: start.sh
      timeout: 300
      runas: ubuntu
