version: "3.7"
services:
  app:
    container_name: app
    image: 238507319080.dkr.ecr.us-east-2.amazonaws.com/f1ntu4l:latest
    restart: always
    depends_on:
      - db
    command: yarn dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: iic2513
      DB_HOST: db
    ports:
      - "80:3000"

  db:
    container_name: db
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: iic2513